# Generated by Django 3.1.2 on 2020-10-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube_id',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
