# Generated by Django 3.1.2 on 2020-10-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_lesson_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='youtube_id',
            field=models.CharField(max_length=32),
        ),
    ]
